spring:
  main:
    web-application-type: none
    banner-mode: off              # disable banner for stdio mode

  ai:
    mcp:
      server:
        stdio: true                     # enable stdio mode

# disable logging for stdio mode
logging:
  level:
    root: OFF