spring:
  application:
    name: spring-ai-mcp-server

  main:
    web-application-type: none
    banner-mode: off              # disable banner for stdio mode

  ai:
    mcp:
      server:
        stdio: true
        name: spring-ai-mcp-server
        version: 0.0.1

# disable logging for stdio mode
logging:
  level:
    root: OFF